---
# tasks file for tomcat
  - name: Setting up minimal tomcat environment
    block:
    - name: update cache
      yum: 
        update_cache: true

    - name: install default-jdk as java dependancy
      yum: 
        name: java-1.8*
        state: present 
        
    - name: create tomcat group if not exists
      group: 
        name: tomcat
        gid: 1900
        state: present

    - name: create user to run java program
      user: 
        name: tomcat
        create_home: true
        home: /opt/tomcat
        system: true
        group: tomcat
        shell: /bin/false 
        uid: 1900

    - name: Download tomcat archive
      get_url: 
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
        dest: /opt/apache-tomcat-9.0.71.tar.gz

    - name: Untar the archive 
      unarchive:
        src: /opt/apache-tomcat-9.0.71.tar.gz
        dest: /opt/tomcat
        remote_src: true

    - name: assign permission to directory
      file: 
        path: /opt/tomcat/apache-tomcat-9.0.71
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
        mode: u=rwx,g=rwx,o=r

    - name: assign executable permission to all binaries
      shell: chmod u+x,g+x /opt/tomcat/apache-tomcat-9.0.71/bin/*.sh 

    - name: copy the tomcat.service file to system directory
      copy: 
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service

    - name: reload system daemon
      shell: systemctl daemon-reload 
      notify: 
      - start_tomcat
    rescue: 
    - name: Making sure all tasks are done successfully
      debug: 
        msg: "failed task on tomcat environment setup phase is \"{{ ansible_failed_task.name }}\""

